name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend-react/**"

permissions:
  id-token: write
  contents: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-react
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend-react/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Unit Test
        run: npm run test

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: https://s83y2xi23f.execute-api.ap-northeast-1.amazonaws.com

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::634454708615:role/github-actions-deploy
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://my-app-frontend-634454708615-ap-northeast-1-an --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E1VS7XPHLE2S16 --paths "/*"
